/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CampInfo = IDL.Record({
  'timing' : IDL.Text,
  'instructor' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCamp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllCamps' : IDL.Func([], [IDL.Vec(CampInfo)], ['query']),
  'getCamp' : IDL.Func([IDL.Text], [CampInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CampInfo = IDL.Record({
    'timing' : IDL.Text,
    'instructor' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addCamp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllCamps' : IDL.Func([], [IDL.Vec(CampInfo)], ['query']),
    'getCamp' : IDL.Func([IDL.Text], [CampInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };